blacklist: []
build_space: build_amd64
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel_amd64
extend_path: /opt/ros/melodic
install: false
install_space: install_amd64
isolate_install: false
jobs_args:
- -j8
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
