// Generated by gencpp from file imu_zero/ImuZeroAngleResponse.msg
// DO NOT EDIT!


#ifndef IMU_ZERO_MESSAGE_IMUZEROANGLERESPONSE_H
#define IMU_ZERO_MESSAGE_IMUZEROANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_zero
{
template <class ContainerAllocator>
struct ImuZeroAngleResponse_
{
  typedef ImuZeroAngleResponse_<ContainerAllocator> Type;

  ImuZeroAngleResponse_()
    {
    }
  ImuZeroAngleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImuZeroAngleResponse_

typedef ::imu_zero::ImuZeroAngleResponse_<std::allocator<void> > ImuZeroAngleResponse;

typedef boost::shared_ptr< ::imu_zero::ImuZeroAngleResponse > ImuZeroAngleResponsePtr;
typedef boost::shared_ptr< ::imu_zero::ImuZeroAngleResponse const> ImuZeroAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace imu_zero

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_zero/ImuZeroAngleResponse";
  }

  static const char* value(const ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuZeroAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::imu_zero::ImuZeroAngleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IMU_ZERO_MESSAGE_IMUZEROANGLERESPONSE_H
