// Generated by gencpp from file imu_zero/ImuZeroAngle.msg
// DO NOT EDIT!


#ifndef IMU_ZERO_MESSAGE_IMUZEROANGLE_H
#define IMU_ZERO_MESSAGE_IMUZEROANGLE_H

#include <ros/service_traits.h>


#include <imu_zero/ImuZeroAngleRequest.h>
#include <imu_zero/ImuZeroAngleResponse.h>


namespace imu_zero
{

struct ImuZeroAngle
{

typedef ImuZeroAngleRequest Request;
typedef ImuZeroAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuZeroAngle
} // namespace imu_zero


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_zero::ImuZeroAngle > {
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::imu_zero::ImuZeroAngle&) { return value(); }
};

template<>
struct DataType< ::imu_zero::ImuZeroAngle > {
  static const char* value()
  {
    return "imu_zero/ImuZeroAngle";
  }

  static const char* value(const ::imu_zero::ImuZeroAngle&) { return value(); }
};


// service_traits::MD5Sum< ::imu_zero::ImuZeroAngleRequest> should match
// service_traits::MD5Sum< ::imu_zero::ImuZeroAngle >
template<>
struct MD5Sum< ::imu_zero::ImuZeroAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_zero::ImuZeroAngle >::value();
  }
  static const char* value(const ::imu_zero::ImuZeroAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_zero::ImuZeroAngleRequest> should match
// service_traits::DataType< ::imu_zero::ImuZeroAngle >
template<>
struct DataType< ::imu_zero::ImuZeroAngleRequest>
{
  static const char* value()
  {
    return DataType< ::imu_zero::ImuZeroAngle >::value();
  }
  static const char* value(const ::imu_zero::ImuZeroAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_zero::ImuZeroAngleResponse> should match
// service_traits::MD5Sum< ::imu_zero::ImuZeroAngle >
template<>
struct MD5Sum< ::imu_zero::ImuZeroAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_zero::ImuZeroAngle >::value();
  }
  static const char* value(const ::imu_zero::ImuZeroAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_zero::ImuZeroAngleResponse> should match
// service_traits::DataType< ::imu_zero::ImuZeroAngle >
template<>
struct DataType< ::imu_zero::ImuZeroAngleResponse>
{
  static const char* value()
  {
    return DataType< ::imu_zero::ImuZeroAngle >::value();
  }
  static const char* value(const ::imu_zero::ImuZeroAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_ZERO_MESSAGE_IMUZEROANGLE_H
