(cl:defpackage talon_swerve_drive_controller-srv
  (:use )
  (:export
   "MOTIONPROFILE"
   "<MOTIONPROFILE-REQUEST>"
   "MOTIONPROFILE-REQUEST"
   "<MOTIONPROFILE-RESPONSE>"
   "MOTIONPROFILE-RESPONSE"
   "SETXY"
   "<SETXY-REQUEST>"
   "SETXY-REQUEST"
   "<SETXY-RESPONSE>"
   "SETXY-RESPONSE"
   "WHEELPOS"
   "<WHEELPOS-REQUEST>"
   "WHEELPOS-REQUEST"
   "<WHEELPOS-RESPONSE>"
   "WHEELPOS-RESPONSE"
  ))

