blacklist: []
build_space: build_aarch64
catkin_make_args: []
cmake_args:
- -DCMAKE_TOOLCHAIN_FILE=$Home/Swerve_ws/aarch64toolchain.cmake
- -DCMAKE_CROSS_COMPILE_PREFIX=$HOME/Swerve_ws/aarch64_root
devel_layout: linked
devel_space: devel_aarch64
extend_path: null
install: false
install_space: install_aarch64
isolate_install: false
jobs_args:
- -j8
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
