// Generated by gencpp from file talon_swerve_drive_controller/MotionProfile.msg
// DO NOT EDIT!


#ifndef TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_MOTIONPROFILE_H
#define TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_MOTIONPROFILE_H

#include <ros/service_traits.h>


#include <talon_swerve_drive_controller/MotionProfileRequest.h>
#include <talon_swerve_drive_controller/MotionProfileResponse.h>


namespace talon_swerve_drive_controller
{

struct MotionProfile
{

typedef MotionProfileRequest Request;
typedef MotionProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotionProfile
} // namespace talon_swerve_drive_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::talon_swerve_drive_controller::MotionProfile > {
  static const char* value()
  {
    return "823f7df5a442d751c5c3d88388259334";
  }

  static const char* value(const ::talon_swerve_drive_controller::MotionProfile&) { return value(); }
};

template<>
struct DataType< ::talon_swerve_drive_controller::MotionProfile > {
  static const char* value()
  {
    return "talon_swerve_drive_controller/MotionProfile";
  }

  static const char* value(const ::talon_swerve_drive_controller::MotionProfile&) { return value(); }
};


// service_traits::MD5Sum< ::talon_swerve_drive_controller::MotionProfileRequest> should match
// service_traits::MD5Sum< ::talon_swerve_drive_controller::MotionProfile >
template<>
struct MD5Sum< ::talon_swerve_drive_controller::MotionProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::talon_swerve_drive_controller::MotionProfile >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::MotionProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::talon_swerve_drive_controller::MotionProfileRequest> should match
// service_traits::DataType< ::talon_swerve_drive_controller::MotionProfile >
template<>
struct DataType< ::talon_swerve_drive_controller::MotionProfileRequest>
{
  static const char* value()
  {
    return DataType< ::talon_swerve_drive_controller::MotionProfile >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::MotionProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::talon_swerve_drive_controller::MotionProfileResponse> should match
// service_traits::MD5Sum< ::talon_swerve_drive_controller::MotionProfile >
template<>
struct MD5Sum< ::talon_swerve_drive_controller::MotionProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::talon_swerve_drive_controller::MotionProfile >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::MotionProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::talon_swerve_drive_controller::MotionProfileResponse> should match
// service_traits::DataType< ::talon_swerve_drive_controller::MotionProfile >
template<>
struct DataType< ::talon_swerve_drive_controller::MotionProfileResponse>
{
  static const char* value()
  {
    return DataType< ::talon_swerve_drive_controller::MotionProfile >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::MotionProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_MOTIONPROFILE_H
