// Generated by gencpp from file talon_swerve_drive_controller/SetXY.msg
// DO NOT EDIT!


#ifndef TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXY_H
#define TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXY_H

#include <ros/service_traits.h>


#include <talon_swerve_drive_controller/SetXYRequest.h>
#include <talon_swerve_drive_controller/SetXYResponse.h>


namespace talon_swerve_drive_controller
{

struct SetXY
{

typedef SetXYRequest Request;
typedef SetXYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetXY
} // namespace talon_swerve_drive_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::talon_swerve_drive_controller::SetXY > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXY&) { return value(); }
};

template<>
struct DataType< ::talon_swerve_drive_controller::SetXY > {
  static const char* value()
  {
    return "talon_swerve_drive_controller/SetXY";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXY&) { return value(); }
};


// service_traits::MD5Sum< ::talon_swerve_drive_controller::SetXYRequest> should match
// service_traits::MD5Sum< ::talon_swerve_drive_controller::SetXY >
template<>
struct MD5Sum< ::talon_swerve_drive_controller::SetXYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::talon_swerve_drive_controller::SetXY >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::SetXYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::talon_swerve_drive_controller::SetXYRequest> should match
// service_traits::DataType< ::talon_swerve_drive_controller::SetXY >
template<>
struct DataType< ::talon_swerve_drive_controller::SetXYRequest>
{
  static const char* value()
  {
    return DataType< ::talon_swerve_drive_controller::SetXY >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::SetXYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::talon_swerve_drive_controller::SetXYResponse> should match
// service_traits::MD5Sum< ::talon_swerve_drive_controller::SetXY >
template<>
struct MD5Sum< ::talon_swerve_drive_controller::SetXYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::talon_swerve_drive_controller::SetXY >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::SetXYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::talon_swerve_drive_controller::SetXYResponse> should match
// service_traits::DataType< ::talon_swerve_drive_controller::SetXY >
template<>
struct DataType< ::talon_swerve_drive_controller::SetXYResponse>
{
  static const char* value()
  {
    return DataType< ::talon_swerve_drive_controller::SetXY >::value();
  }
  static const char* value(const ::talon_swerve_drive_controller::SetXYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXY_H
