// Generated by gencpp from file talon_swerve_drive_controller/SetXYRequest.msg
// DO NOT EDIT!


#ifndef TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYREQUEST_H
#define TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talon_swerve_drive_controller
{
template <class ContainerAllocator>
struct SetXYRequest_
{
  typedef SetXYRequest_<ContainerAllocator> Type;

  SetXYRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  SetXYRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetXYRequest_

typedef ::talon_swerve_drive_controller::SetXYRequest_<std::allocator<void> > SetXYRequest;

typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYRequest > SetXYRequestPtr;
typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYRequest const> SetXYRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator1> & lhs, const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator1> & lhs, const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace talon_swerve_drive_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talon_swerve_drive_controller/SetXYRequest";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetXYRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talon_swerve_drive_controller::SetXYRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYREQUEST_H
