// Generated by gencpp from file talon_swerve_drive_controller/SetXYResponse.msg
// DO NOT EDIT!


#ifndef TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYRESPONSE_H
#define TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talon_swerve_drive_controller
{
template <class ContainerAllocator>
struct SetXYResponse_
{
  typedef SetXYResponse_<ContainerAllocator> Type;

  SetXYResponse_()
    {
    }
  SetXYResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetXYResponse_

typedef ::talon_swerve_drive_controller::SetXYResponse_<std::allocator<void> > SetXYResponse;

typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYResponse > SetXYResponsePtr;
typedef boost::shared_ptr< ::talon_swerve_drive_controller::SetXYResponse const> SetXYResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace talon_swerve_drive_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talon_swerve_drive_controller/SetXYResponse";
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetXYResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::talon_swerve_drive_controller::SetXYResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TALON_SWERVE_DRIVE_CONTROLLER_MESSAGE_SETXYRESPONSE_H
