// Generated by gencpp from file navx_offset_controller/NavXSrv.msg
// DO NOT EDIT!


#ifndef NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRV_H
#define NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRV_H

#include <ros/service_traits.h>


#include <navx_offset_controller/NavXSrvRequest.h>
#include <navx_offset_controller/NavXSrvResponse.h>


namespace navx_offset_controller
{

struct NavXSrv
{

typedef NavXSrvRequest Request;
typedef NavXSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavXSrv
} // namespace navx_offset_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navx_offset_controller::NavXSrv > {
  static const char* value()
  {
    return "1b1594d2b74931ef8fe7be8e2d594455";
  }

  static const char* value(const ::navx_offset_controller::NavXSrv&) { return value(); }
};

template<>
struct DataType< ::navx_offset_controller::NavXSrv > {
  static const char* value()
  {
    return "navx_offset_controller/NavXSrv";
  }

  static const char* value(const ::navx_offset_controller::NavXSrv&) { return value(); }
};


// service_traits::MD5Sum< ::navx_offset_controller::NavXSrvRequest> should match
// service_traits::MD5Sum< ::navx_offset_controller::NavXSrv >
template<>
struct MD5Sum< ::navx_offset_controller::NavXSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navx_offset_controller::NavXSrv >::value();
  }
  static const char* value(const ::navx_offset_controller::NavXSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navx_offset_controller::NavXSrvRequest> should match
// service_traits::DataType< ::navx_offset_controller::NavXSrv >
template<>
struct DataType< ::navx_offset_controller::NavXSrvRequest>
{
  static const char* value()
  {
    return DataType< ::navx_offset_controller::NavXSrv >::value();
  }
  static const char* value(const ::navx_offset_controller::NavXSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navx_offset_controller::NavXSrvResponse> should match
// service_traits::MD5Sum< ::navx_offset_controller::NavXSrv >
template<>
struct MD5Sum< ::navx_offset_controller::NavXSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navx_offset_controller::NavXSrv >::value();
  }
  static const char* value(const ::navx_offset_controller::NavXSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navx_offset_controller::NavXSrvResponse> should match
// service_traits::DataType< ::navx_offset_controller::NavXSrv >
template<>
struct DataType< ::navx_offset_controller::NavXSrvResponse>
{
  static const char* value()
  {
    return DataType< ::navx_offset_controller::NavXSrv >::value();
  }
  static const char* value(const ::navx_offset_controller::NavXSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRV_H
