// Generated by gencpp from file navx_offset_controller/NavXSrvResponse.msg
// DO NOT EDIT!


#ifndef NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRVRESPONSE_H
#define NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navx_offset_controller
{
template <class ContainerAllocator>
struct NavXSrvResponse_
{
  typedef NavXSrvResponse_<ContainerAllocator> Type;

  NavXSrvResponse_()
    {
    }
  NavXSrvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavXSrvResponse_

typedef ::navx_offset_controller::NavXSrvResponse_<std::allocator<void> > NavXSrvResponse;

typedef boost::shared_ptr< ::navx_offset_controller::NavXSrvResponse > NavXSrvResponsePtr;
typedef boost::shared_ptr< ::navx_offset_controller::NavXSrvResponse const> NavXSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace navx_offset_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navx_offset_controller/NavXSrvResponse";
  }

  static const char* value(const ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavXSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::navx_offset_controller::NavXSrvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAVX_OFFSET_CONTROLLER_MESSAGE_NAVXSRVRESPONSE_H
