// Generated by gencpp from file frc_msgs/PDPData.msg
// DO NOT EDIT!


#ifndef FRC_MSGS_MESSAGE_PDPDATA_H
#define FRC_MSGS_MESSAGE_PDPDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace frc_msgs
{
template <class ContainerAllocator>
struct PDPData_
{
  typedef PDPData_<ContainerAllocator> Type;

  PDPData_()
    : header()
    , voltage(0.0)
    , temperature(0.0)
    , totalCurrent(0.0)
    , totalPower(0.0)
    , totalEnergy(0.0)
    , current()  {
      current.assign(0.0);
  }
  PDPData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , voltage(0.0)
    , temperature(0.0)
    , totalCurrent(0.0)
    , totalPower(0.0)
    , totalEnergy(0.0)
    , current()  {
  (void)_alloc;
      current.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _totalCurrent_type;
  _totalCurrent_type totalCurrent;

   typedef double _totalPower_type;
  _totalPower_type totalPower;

   typedef double _totalEnergy_type;
  _totalEnergy_type totalEnergy;

   typedef boost::array<double, 16>  _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::frc_msgs::PDPData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frc_msgs::PDPData_<ContainerAllocator> const> ConstPtr;

}; // struct PDPData_

typedef ::frc_msgs::PDPData_<std::allocator<void> > PDPData;

typedef boost::shared_ptr< ::frc_msgs::PDPData > PDPDataPtr;
typedef boost::shared_ptr< ::frc_msgs::PDPData const> PDPDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frc_msgs::PDPData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frc_msgs::PDPData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::frc_msgs::PDPData_<ContainerAllocator1> & lhs, const ::frc_msgs::PDPData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.voltage == rhs.voltage &&
    lhs.temperature == rhs.temperature &&
    lhs.totalCurrent == rhs.totalCurrent &&
    lhs.totalPower == rhs.totalPower &&
    lhs.totalEnergy == rhs.totalEnergy &&
    lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::frc_msgs::PDPData_<ContainerAllocator1> & lhs, const ::frc_msgs::PDPData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace frc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::frc_msgs::PDPData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frc_msgs::PDPData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frc_msgs::PDPData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frc_msgs::PDPData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frc_msgs::PDPData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frc_msgs::PDPData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frc_msgs::PDPData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0499c093ceea29bec4557205d989a1c6";
  }

  static const char* value(const ::frc_msgs::PDPData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0499c093ceea29beULL;
  static const uint64_t static_value2 = 0xc4557205d989a1c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::frc_msgs::PDPData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frc_msgs/PDPData";
  }

  static const char* value(const ::frc_msgs::PDPData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frc_msgs::PDPData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 voltage\n"
"float64 temperature\n"
"float64 totalCurrent\n"
"float64 totalPower\n"
"float64 totalEnergy\n"
"\n"
"float64[16] current\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::frc_msgs::PDPData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frc_msgs::PDPData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.voltage);
      stream.next(m.temperature);
      stream.next(m.totalCurrent);
      stream.next(m.totalPower);
      stream.next(m.totalEnergy);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PDPData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frc_msgs::PDPData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frc_msgs::PDPData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    s << indent << "totalCurrent: ";
    Printer<double>::stream(s, indent + "  ", v.totalCurrent);
    s << indent << "totalPower: ";
    Printer<double>::stream(s, indent + "  ", v.totalPower);
    s << indent << "totalEnergy: ";
    Printer<double>::stream(s, indent + "  ", v.totalEnergy);
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRC_MSGS_MESSAGE_PDPDATA_H
